"""empty message

Revision ID: b6be239e12ea
Revises: 
Create Date: 2025-05-17 21:32:36.593250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6be239e12ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Filename', sa.String(length=250), nullable=False),
    sa.Column('Width', sa.Integer(), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Roi_X1', sa.Integer(), nullable=False),
    sa.Column('Roi_Y1', sa.Integer(), nullable=False),
    sa.Column('Roi_X2', sa.Integer(), nullable=False),
    sa.Column('Roi_Y2', sa.Integer(), nullable=False),
    sa.Column('ClassId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    # ### end Alembic commands ###
